# irods-provisioner
#
# playbooks/irods-cluster.yml - Ansible playbook for configuring a test iRODS cluster
# Author: Ilari Korhonen, KTH Royal Institute of Technology
#
# Copyright (C) 2016-2017 KTH Royal Institute of Technology. All rights reserved.
# See LICENSE file for more information.

---

- hosts: irods
  become_user: root

  tasks:
    - name: register git repo commit id
      local_action: shell git rev-parse HEAD
      become: no
      register: git_commit_id

    - name: "Build hosts file"
      lineinfile: dest=/etc/hosts regexp='.*{{ item }}$' line="{{ hostvars[item].ansible_eth1.ipv4.address }} {{item}}" state=present
      when: hostvars[item].ansible_eth1.ipv4.address is defined
      with_items: "{{ groups['all'] }}"

    - name: build provisioner manifest file
      template: src="../templates/irods-provisioner.manifest.j2" dest="/etc/irods-provisioner.manifest" mode=0644 owner=root group=root

    - name: necessary package repositories
      yum: name={{ item }} state=latest
      with_items:
        - epel-release

    - name: necessary base packages
      yum: name={{ item }} state=latest
      with_items:
        - psmisc
        - net-tools
        - htop
        - iotop
        - iftop
        - python-psycopg2
        - httpd
        - php
        - wget

    - name: import iRODS package repo signing key
      shell: rpm --import https://packages.irods.org/irods-signing-key.asc

    - name: iRODS package repository for yum
      get_url:
        url: https://packages.irods.org/renci-irods.yum.repo
        dest: /etc/yum.repos.d/renci-irods.yum.repo

- hosts: irods-icat
  become_user: root
  
  roles:
    - role: postgres 

    - role: irods-icat

    - role: pgadmin

    - role: emc-metalnx-rmd

- hosts: irods-resource
  become_user: root

  roles:
    - role: irods-resource

    - role: davrods

    - role: emc-metalnx-rmd

- hosts: irods-frontend
  become_user: root

  roles:
    - role: postgres

    - role: emc-metalnx-web

    - role: b2stage-gridftp
