# irods-provisioner
#
# playbooks/irods-icat.yml - Ansible playbook for configuring an iRODS iCAT
# Author: Ilari Korhonen, KTH Royal Institute of Technology

---

- hosts: all
  become_user: root

  tasks:
    - name: "Build hosts file"
      lineinfile: dest=/etc/hosts regexp='.*{{ item }}$' line="{{ hostvars[item].ansible_eth1.ipv4.address }} {{item}}" state=present
      when: hostvars[item].ansible_eth1.ipv4.address is defined
      with_items: "{{ groups['all'] }}" 

    - name: necessary base repositories
      yum: name={{ item }} state=latest
      with_items:
        - epel-release

    - name: necessary base packages
      yum: name={{ item }} state=latest
      with_items:
        - psmisc
        - net-tools
        - htop
        - iotop
        - iftop
        - python-psycopg2
        - httpd
        - php
        - wget

    - name: import iRODS package repo signing key
      shell: rpm --import https://packages.irods.org/irods-signing-key.asc

    - name: iRODS package repository for yum
      shell: wget -qO - https://packages.irods.org/renci-irods.yum.repo > /etc/yum.repos.d/renci-irods.yum.repo
      args:
        creates: /etc/yum.repos.d/renci-irods.yum.repo

- hosts: irods-icat
  become_user: root
  
  roles:
    - role: postgres 

    - role: irods-icat

    - role: pgadmin

- hosts: irods-resource
  become_user: root

  roles:
    - role: irods-resource

#    - role: davrods
